version: '3.8'
services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "4200:4200"
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "80:443"
    depends_on:
      - db
  db:
    build: ./postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
